### ISSUE TITLE
Acquisition: sunfoxcz

### ISSUE THREAD

**Issue by foxycode** [contributte/contributte#10]
I'd like to add my packages and few other to Contributte:

From Package | To Package | State |
----------------|--------------|-------|
[Carrooi/Nette-Menu](https://github.com/Carrooi/Nette-Menu) | [contributte/nette-menu](https://github.com/contributte/menu-control) | :heavy_check_mark:
[Vrtak-CZ/NewRelic-Tracy](https://github.com/Vrtak-CZ/NewRelic-Tracy) | contributte/newrelic | :heavy_check_mark:
[Vrtak-CZ/NewRelic-Nette](https://github.com/Vrtak-CZ/NewRelic-Nette) | contributte/newrelic | :heavy_check_mark:

I am maintainer of `Vrtak-CZ/NewRelic` packages. Current maintainer of `Carrooi/Nette-Menu` package seems to don't have time any more and I am using this package heavily.

**Comment by vojtamares** [comment]
Hi, thank you for your work and cotnributtion to Nette community and will to contrbutte to Contributte. The decision is up to @f3l1x, I think.

But I have one question, can you maintain those packages if they would be migrated to Contributte or not?

Since the Contributte acquisition requires major changes to the repository and composer package, can you do it? If so, I think @f3l1x can create empty repositories for these packages and you can send a PR.

**Comment by foxycode** [comment]
@vojtamares Of course I can do needed changes and maintain packages.

**Comment by f3l1x** [comment]
Looks good to me. We will arrange the transfer during the summer. I know that's a long time, but the cucumber season is approaching. xD

**Comment by f3l1x** [comment]
@foxycode Have you contacted Vrtak about merging and moving these packages under contributte?

**Comment by foxycode** [comment]
@f3l1x Vrtak agreed to fork `NewRelic` repositories under `Contributte` and deprecate his own package. Please fork [Vrtak-CZ/NewRelic-Nette](https://github.com/Vrtak-CZ/NewRelic-Nette) under `contributte/newrelic` and I'll do the rest.

**Comment by mabar** [comment]
@foxycode Is it really needed to fork? Repository can be transfered completely.

**Comment by foxycode** [comment]
@mabar It is possible to move to organisation, where Vrtak don't have permissions? How he can do it?

**Comment by mabar** [comment]
Create a temporary organization, transfer repository and give permissions to owner of targer organization.

**Comment by davidkudera** [comment]
Hi, I transferred the menu package to a new organization https://github.com/carrooi-to-contributte/Nette-Menu, where I invited @f3l1x too.

@foxycode, @f3l1x thanks for this possibility to keep my package alive. Even though I didn't use Nette in the last 2 years, I'm using contributte packages daily, so this is the best place where the package could be. :+1: 

Also, thanks @mabar for the "how-to".

**Comment by foxycode** [comment]
@f3l1x Any progress with Nette-Menu?

**Comment by f3l1x** [comment]
Hi @foxycode, Nette-Menu is still in Carrooi org. What should I do?

<img width="232" alt="Screenshot 2019-10-30 at 12 04 28" src="https://user-images.githubusercontent.com/538058/67852841-7950dd00-fb0d-11e9-9e87-e29f5eed1142.png">

**Comment by davidkudera** [comment]
@f3l1x yep, I moved it back to Carrooi after about 2 weeks of no action. Should I move it again?

**Comment by f3l1x** [comment]
Give me permission for that repo and I will move it here. Thanks.

**Comment by davidkudera** [comment]
Ok, so I did what I did the last time - I moved the repo here https://github.com/carrooi-to-contributte/Nette-Menu

Your invitation to that temp organization is still in pending state:

![Výběr_600](https://user-images.githubusercontent.com/1174072/67853191-49eea000-fb0e-11e9-94fa-0b160ee89668.png)

**Comment by f3l1x** [comment]
Done, thanks.

**Comment by foxycode** [comment]
@f3l1x Can I get acc to new repo? Will you create packagist package too?

**Comment by davidkudera** [comment]
I thank all of you too :beers:

**Comment by f3l1x** [comment]
@foxycode You've got access. Lets move discussion to repo issues.

**Comment by f3l1x** [comment]
@foxycode Any news about newrelic?

**Comment by foxycode** [comment]
@f3l1x Unfortunately, Patrik doesn't responding to my mails. We can make fork if you want.

**Comment by f3l1x** [comment]
Hey @foxycode, what can I do for move this out? :-) Should I talk with @vrtak-CZ?

**Comment by foxycode** [comment]
@f3l1x You can try, but I tried to send him mail many times with no answer. We can always do a fork.

**Comment by Vrtak-CZ** [comment]
TMP organization here https://github.com/tmp-move-repost-assdfas owner invite send to @f3l1x

**Comment by f3l1x** [comment]
Thanks @Vrtak-CZ. You're the best. :-)

![image](https://user-images.githubusercontent.com/538058/81571336-17b5d900-93a2-11ea-83cb-cb3c8797603b.png)

**Comment by f3l1x** [comment]
I think our job is done. Feel free to open it again for another migration. :-) Thank you all guys. @foxycode @Vrtak-CZ
