### ISSUE TITLE
Project skeletons for Contributte, Nettrine, etc.

### ISSUE THREAD

**Issue by vojtamares** [contributte/contributte#11]
At [NetteCamp](https://www.nettecamp.cz/) we heard many voices saying that there is not enough examples. That is being worked on.

But why should we stop there? I suggest we create some project skeletons (like `nette/web-project`) with usage of [Contributte](https://github.com/contributte) packages, e.g. `contributte/skeleton` and for [Nettrine](https://github.com/nettrine) `nettrine/skeleton`. 

And we do not have to stop there, let's create an example of how to create Nette app with [Dockette](https://github.com/dockette).

And as mentioned at NetteCamp, we should write some articles about it.

The name doesn't have to be `*/skeleton` it can be `*/web-project` so we are consistent across Nette ecosystem.

I can take care of it and then submit it for a review.

---

Also, I would add these project skeletons to homepage of Contributte so people see it right away.

What do you think @f3l1x ?

**Comment by mabar** [comment]
web-project or project, skeleton sounds kinda oddly

**Comment by vojtamares** [comment]
@mabar well the name itself isn't that important, the important thing is that such a thing exists I would say.

The thought behind it is the repository allowing people to quickly jump into using these packages.

And I do not thing that `planette/nutella-project` is the greatest to start with, I see it more as an example rather than base project such as `nette/web-project` or `nette/sandbox`.

The naming itself is odd anyway, but I would take to a count other existing projects such as symfony where you have `symfony/skeleton` (and `symfony/website-skeleton`).

On the other hand Symfony (for example) has it's own cli tool. So it is very easy to create new project with it
```bash
symfony new <project name>
```

**Comment by f3l1x** [comment]
- Bare repository (template) for libraries: https://github.com/contributte/bare
- Demo projects
    - https://github.com/planette/nutella-project/
    - https://github.com/planette/forest-project/
    - https://github.com/planette/cindy-project/
    - https://github.com/planette/snow-project/
