### ISSUE TITLE
COFIS CZ, s.r.o.

### ISSUE THREAD

**Issue by artemevsin** [contributte/contributte#12]
# New Truster

- Name: COFIS CZ, s.r.o.
- URL: https://www.cofis.cz/
- Image: https://www.cofis.cz/logo-512.png

**Comment by f3l1x** [comment]
Done. Thanks. 

![image](https://user-images.githubusercontent.com/538058/81107432-79e08b00-8f17-11ea-9eeb-0e3de8d612e6.png)
