### ISSUE TITLE
FAPI Business s.r.o.

### ISSUE THREAD

**Issue by slischka** [contributte/contributte#13]
# New Truster

- Name: FAPI Business s.r.o.
- URL: https://fapi.cz
- Image: https://files.slack.com/files-pri/T02N6DGCB-F013ESW1N4R/fapi_logo.png

**Comment by vojtamares** [comment]
Hi, thank you for submtting another company to **Trusted by** list, unfortunately the Slack URL is unavailable unless you are signed into the workspace. Can you please provide another URL for the logo?

**Comment by slischka** [comment]
Ah sorry, I was sure this will work :D There is the image:
![fapi_logo](https://user-images.githubusercontent.com/19595920/81075136-40ddf180-8eea-11ea-8aa7-5fe3d4827655.png)

**Comment by f3l1x** [comment]
Done, thanks. :-)

![image](https://user-images.githubusercontent.com/538058/81107442-7d741200-8f17-11ea-91d3-72bbf0504126.png)
