### ISSUE TITLE
2htech s.r.o.

### ISSUE THREAD

**Issue by tomashaubert** [contributte/contributte#14]
# New Truster

- Name: 2htech s.r.o.
- URL: https://2htech.cz
- Image: https://2htech.cz/wp-content/uploads/logo/512x512.png

**Comment by f3l1x** [comment]
Done. Thanks Tome ;-)

![image](https://user-images.githubusercontent.com/538058/81107415-73521380-8f17-11ea-8c97-8046b6802ce1.png)
