### ISSUE TITLE
D5T5 s.r.o.

### ISSUE THREAD

**Issue by SiViN** [contributte/contributte#15]
# New Truster

- Name: D5T5 s.r.o.
- URL: https://d5t5.com/
- Image: https://d5t5.com/assets/images/d5t5-logo-512x512.png

♥

**Comment by f3l1x** [comment]
Done. 
![image](https://user-images.githubusercontent.com/538058/81167076-ddf56480-8f94-11ea-8a7e-c89e86de32f3.png) :-)
