### ISSUE TITLE
New Truster - Emailkampane.cz

### ISSUE THREAD

**Issue by martinvitak** [contributte/contributte#17]
# New Truster

- Name: Emailkampane.cz
- URL: https://www.emailkampane.cz/
- Image: https://www.emailkampane.cz/files/obrazky/ek_logo.png

Thanks :)

**Comment by f3l1x** [comment]
![image](https://user-images.githubusercontent.com/538058/81269143-35eda300-9049-11ea-8d3a-e7e91283bc64.png)

Done. Thanks. 👍
