### ISSUE TITLE
Acquisition: Arachne

### ISSUE THREAD

**Issue by f3l1x** [contributte/contributte#2]
After the long time, we're going to adopt some Arachne packages. :-)

Thanks @enumag, @mabar 

Packages:

| Package | Standalone | Package | Status
|-|-|-|-|
| Arachne/Codeception | yes | [contributte/codeception](https://github.com/contributte/codeception) | done |
| Arachne/ServiceCollections | no | [contributte/di](https://github.com/contributte/di) | next

**Comment by mabar** [comment]
@enumag

service collections - I've seen that you discussed about them with David in nette/di#178. Are they still required or did you found new nette features good enough?

security and verifier - I was thinking about these packages for a long time. I found that I love them and I am grateful for them.
But I have one which I would like to implement before moving these into Contributte. 
It's a return of `Nette\Security\User`. I understand reasons why it's not used but I think we cannot simply drop it.
It is required by `Nette\Application\UI\Presenter::(store|restore)Request` and I don't see an easy way how to reimplement these methods.
Solution would be in interface for nette user, just with `getId()`. In that way we could have our own user which would be also a storage for all its identities.
It would also simplify my use case where I have a single user which is verified against multiple firewalls.

**Comment by enumag** [comment]
@mabar I didn't watch recent nette/di changes. Is the thing dg come up with in that discussion about accessors for multiple services implemented? If it is then ServiceCollections are no longer necessary (or only for Arachne/Forms) and the packages can be adapted to use the new nette/di features.

As for store/restoreRequest in my opinion the usage of user in these methods is completely unnecessary. I really didn't need `User` for anything in my CMS.

In any case a "User" is a value object with data about the person using the system and therefore should not be a service. If you feel something like `Nette\Security\User` is necessary then so be it but for gods sake please rename it.

**Comment by mabar** [comment]
Seems like it is implemented. But I am not sure, if it supports `get($foo)` or just `getFoo(); getBar();` https://github.com/nette/di/commit/94a66aa2bc8370283b3bbd10131d45be16cad2bc

User is used in (re)storeRequest used as a security feature. It prevents user from sending anyone a link with stored url.

**Comment by enumag** [comment]
> User in (re)storeRequest is used as a security element. It prevents from sending anyone a link with stored url.

The requests are stored in your session so the link would not work anyway.

**Comment by enumag** [comment]
> Seems like it is implemented. But I am not sure, if it supports get($foo) or just getFoo(); getBar(); nette/di@94a66aa

I believe that's a completely unrelated feature. It's just a sort of "multifactory". Honestly I have no idea what that would be good for. Anyway it can't work as a replacement for ServiceCollections resolvers.

**Comment by f3l1x** [comment]
Hey. Let's move things. :-) I am suggesting to take a look more time at arachne packages.

**Comment by enumag** [comment]
Would be nice. Note that they're becoming a bit outdated. I'm focusing on other open source projects so I don't have time to update them to Nette 3 sadly.

**Comment by f3l1x** [comment]
I think we're done for now.  nette/di has evolved. I will keep my eyes on nette/di vs Arachne/ServiceCollections. We will see where things go.
