### ISSUE TITLE
New Truster: Whalebone

### ISSUE THREAD

**Issue by rattuscz** [contributte/contributte#20]
# New Truster

- Name: Whalebone
- URL: https://whalebone.io
- Image: https://avatars.githubusercontent.com/whalebone

Many thanks! :-)

**Comment by f3l1x** [comment]
![image](https://user-images.githubusercontent.com/538058/81269143-35eda300-9049-11ea-8d3a-e7e91283bc64.png)

Done. Thanks. 👍
