### ISSUE TITLE
Beneš & Michl

### ISSUE THREAD

**Issue by eduardstula** [contributte/contributte#21]
# New Truster

- Name: Beneš & Michl
- URL: https://www.benes-michl.cz/
- Image: https://www.benes-michl.cz/public/images/bm_logo_512x512.png

**Comment by f3l1x** [comment]
Done. Welcome on board!

![image](https://user-images.githubusercontent.com/538058/81442485-f5d70f00-9173-11ea-8f16-a5697a35e548.png)
