### ISSUE TITLE
New truster: Redbit s.r.o.

### ISSUE THREAD

**Issue by jakubboucek** [contributte/contributte#23]
# New Truster

- Name: Redbit s.r.o.
- URL: https://www.redbit.cz/
- Image: 
   - Native: https://cdn.redbit.cz/static/redbit.cz/logo/redbit-logo-512px.png
   - Square: https://cdn.redbit.cz/static/redbit.cz/logo/redbit-logo-512px-square.png

Používáme balíčky Contributte v projektech Vyfakturuj.cz a Simplehop.cz.

**Comment by f3l1x** [comment]
Done. :-) Pekne weby.

![image](https://user-images.githubusercontent.com/538058/81572545-a1b27180-93a3-11ea-83b4-49bf6fef28ea.png)
