### ISSUE TITLE
New Truster

### ISSUE THREAD

**Issue by rtsoftplzen** [contributte/contributte#24]
# RTsoft

- Name: RTsoft
- URL: https://www.rtsoft.cz/
- Image: ![logo](https://user-images.githubusercontent.com/24958302/82556575-513cd000-9b6a-11ea-8bce-eb9e72226706.png)

**Comment by f3l1x** [comment]
![image](https://user-images.githubusercontent.com/538058/82581652-2f0a7880-9b91-11ea-9f33-3a6d09b9f91b.png)

Thank you.
