### ISSUE TITLE
WAME s.r.o.

### ISSUE THREAD

**Issue by wamesro** [contributte/contributte#26]
# New Truster

- Name: WAME s.r.o.
- URL: https://wame.sk/
- Image: https://wame.sk/images/template/wame_logo-512x512.png

Požívame vo veľkom čo sa dá, sme radi že tieto balíčky majú za sebou comunitu ktorá sa tomu venuje aj vo svojom voľnom čase ktorého máme každý málo. Vďaka  týmto balíčkom sme sa aj my naučili ako to robiť správne.

**Comment by f3l1x** [comment]
![image](https://user-images.githubusercontent.com/538058/85017290-863d4200-b16b-11ea-88f9-b0db71ed255d.png)

❤️
