### ISSUE TITLE
New Truster: Freelo.cz

### ISSUE THREAD

**Issue by her-ur** [contributte/contributte#27]
# New Truster

- Name: Freelo.cz
- URL: https://www.freelo.cz
- Image: 
![freelo-logo-rgb](https://user-images.githubusercontent.com/13915017/84981513-fc728200-b134-11ea-8b89-08e0e2e265bf.png)

**Comment by f3l1x** [comment]
![image](https://user-images.githubusercontent.com/538058/85017290-863d4200-b16b-11ea-88f9-b0db71ed255d.png)

❤️
