### ISSUE TITLE
Vioro

### ISSUE THREAD

**Issue by michalhlavka** [contributte/contributte#28]
# New Truster

- Name: Vioro
- URL: vioro.cz
- Image: https://drive.google.com/file/d/1XdPz_V79qrAINtoa8mSPg0wYmF41Li7g/view?usp=sharing

**Comment by f3l1x** [comment]
Thanks @michalhlavka, could you please upload logo 512x512? Thanks.

**Comment by michalhlavka** [comment]
@f3l1x google drive link should be updated

**Comment by f3l1x** [comment]
![image](https://user-images.githubusercontent.com/538058/85033270-0fab3f00-b181-11ea-8073-ce003bdbe199.png)

Once again, send me please real image.

**Comment by michalhlavka** [comment]
Oh my god, I don't see any problem in anonymous tab, but there is an alternative link, sorry for that. 

https://i.imgur.com/zD4oQxq.png

**Comment by f3l1x** [comment]
👍 

![image](https://user-images.githubusercontent.com/538058/85128338-58bacc00-b231-11ea-8de6-77e7616cedec.png)
