### ISSUE TITLE
Flatio

### ISSUE THREAD

**Issue by michalhlavka** [contributte/contributte#29]
# New Truster

- Name: Flatio
- URL: flatio.com
- Image: https://drive.google.com/file/d/164PHvoDwuVMLGxoeIyxZE3VeAqMZDXGo/view?usp=sharing

**Comment by f3l1x** [comment]
👍 

![image](https://user-images.githubusercontent.com/538058/85141923-dd184980-b247-11ea-854c-1f1217ef403a.png)
