### ISSUE TITLE
Roadmap 2018

### ISSUE THREAD

**Issue by f3l1x** [contributte/contributte#3]
This is, *from my point of view*, 2018 roadmap for Contributte environment. 

# Finalize

Transform to contributte (composer, namespace, codesniffer, PHP 7.1):

-  :heavy_check_mark: https://github.com/contributte/dummy-events
-  :heavy_check_mark: https://github.com/contributte/social
- :heavy_check_mark: https://github.com/contributte/deployer-extension
- :heavy_check_mark: https://github.com/contributte/mobilni-platby
- :heavy_check_mark: https://github.com/contributte/nextras-orm-query-object
- :heavy_check_mark: https://github.com/contributte/image-storage
- https://github.com/contributte/api-router
- https://github.com/contributte/api-docu
- https://github.com/contributte/anabelle

# PSR

Create PSR-based repositories for Nette/Contributte applications:

- :heavy_check_mark: https://github.com/contributte/psr7-http-message
- https://github.com/contributte/psr6-caching
- https://github.com/contributte/psr3-logging
- :heavy_check_mark: https://github.com/contributte/psr11-container-interface
 
# New packages

We're still missing some tiny integrations of:

-  :heavy_check_mark: Monolog
- Symfony Validator
- Symfony Translator
- :heavy_check_mark: Redis
- Google
- :heavy_check_mark: Facebook

These packages have their implementations in Kdyby ([Validator](https://github.com/Kdyby/Validator), [Monolog](https://github.com/Kdyby/Monolog), etc..). But Kdyby has unsure feature and Kdyby's integrations are little bit fat (my feelings only). 
# Acquisitions

## Ublaboo :heavy_check_mark:

We're working with @paveljanda on big top-secret project about contributte and ublaboo. First swallow you could noticed in [contributte/application repository](https://github.com/contributte/application/pull/12).

## Arachne

We're working with @mabar / @enumag on back-porting Arachne into Contributte.
See more on solo issue: #2 

# Cleanup

I'm not quite sure what to do with some empty repositories. There're some good ideas and thoughts, but I don't have so much time. Maybe others? We'll see.

- :heavy_check_mark: https://github.com/contributte/model
- :heavy_check_mark: https://github.com/contributte/routing
- https://github.com/contributte/nextras-criteria
- :heavy_check_mark: https://github.com/contributte/symfonier [REMOVED]

# Team

At this time, Contributte organization consists of 10 members.

- @f3l1x
- @benijo 
- @enumag 
- @paveljanda
- @chemix 
- @Crempa 
- @matyx 
- @vody105 
- @mabar 
- @vojtamares 

Thank you guys for being in Contributte and try to do your best. Someones improve 1 repository, someones improve more then 1.

# Website :heavy_check_mark:

Contributte is not a small project, we need a website. I would like to create something similar like this website (https://docusaurus.io/docs/en/installation.html), I like the schema/layout a lot.

We'll probably use Hugo as static generator, unless there'll be big mind-changer in usage.

The game-changer in static sites generators is Vuepress (https://vuepress.vuejs.org/), looks simple and powerfull. But I'm not sure how to handle multi-repo documentation.

We need discuss it deeper.

# Playground :heavy_check_mark:

At Contributte we have the main goal to show working tools to others, thus we are building our [**playground**](https://github.com/contributte/playground).

At this time, there is just api example, which is quite old and contributte/api has been transformed into Apitte. Latest example of working API is in [apitte/playgroud](https://github.com/apitte/playground).

We need more to focus on playground, examples and tutorials to spread our packages. Don't you think guys? Yes, you do. 

Let's create some examples:
- contributte/console 
- contributte/event-dispatcher
- contributte/middlewares
- contributte/forms + recaptcha
- and many others...

# Ideas

I am still active in Java development and there's a cool feature called monads. I would like to have someting similar in Contributte.

Some articles:
- https://examples.javacodegeeks.com/core-java/util/optional/java-8-optional-example/
- https://medium.com/@afcastano/monads-for-java-developers-part-1-the-optional-monad-aa6e797b8a6e
- https://blog.ircmaxell.com/2013/07/taking-monads-to-oop-php.html

**Comment by hrach** [comment]
> Monolog

IMO there is quite great integration in nextras: https://github.com/nextras/tracy-monolog-adapter
There is no additional bloatware, it just adds the needed: connection between Monolog & Nette :)

**Comment by vojtamares** [comment]
@f3l1x there is a typo in link of a package.
It is not `contributte/deployment-extension`, but it is [`contributte/deployer-extension`](https://github.com/contributte/deployer-extension)

It is just a typo but I felt for it at least 100 times already...

**Comment by f3l1x** [comment]
See roadmap for 2019 [#6].

**Comment by f3l1x** [comment]
Recap of year 2018 is also available on our website https://contributte.org/roadmap/recap.html#_2018.
