### ISSUE TITLE
iVenkov

### ISSUE THREAD

**Issue by vojtars** [contributte/contributte#38]
# New Truster

- Name: iVenkov
- URL: [https://www.ivenkov.cz](https://www.ivenkov.cz)
- Image: ![ivenkov-logo](https://user-images.githubusercontent.com/11831233/102353604-4c60c300-3f77-11eb-8cb9-461a235f38b0.png)

API first Website for community building in Czech countryside. All built on Nette framework and of course on contributte libraries. :-)

**Comment by f3l1x** [comment]
Thanks your.

![image](https://user-images.githubusercontent.com/538058/102717988-e9a85800-42e5-11eb-9bd2-373618b789e2.png)
