### ISSUE TITLE
New Truster: MICRORISC s.r.o.

### ISSUE THREAD

**Issue by Roman3349** [contributte/contributte#39]
# New Truster

- Name: MICRORISC s.r.o.
- URL: https://microrisc.com/
- Image: ![microrisc](https://user-images.githubusercontent.com/4655467/102425300-503f2480-400d-11eb-8761-36c03ce7b67e.png)

We use Contributte packages in [an open source web application used to manage the IQRF gateway](https://gitlab.iqrf.org/open-source/iqrf-gateway-webapp/).

**Comment by f3l1x** [comment]
Thank you.

![image](https://user-images.githubusercontent.com/538058/102717991-edd47580-42e5-11eb-8f59-cc2db2cdbb6f.png)
