### ISSUE TITLE
RFC: semver (1.x.y) / zerover (0.x.y)

### ISSUE THREAD

**Issue by f3l1x** [contributte/contributte#4]
We've discussed it internally and here's a statement.

We will continue with 0.x releases as well as needed. When stable version of nette v3.0 will be released, we switch to semver and release our latest versions as 1.0 or others.

Thanks, Felix

**Comment by f3l1x** [comment]
I am thinking about releasing stable versions (v1.0 or higher) with Nette 3.0 and PHP 7.4. To save our time with refactoring to typed properties and other things in PHP 7.4.

**Comment by mabar** [comment]
PHP 7.4 will be released in december, but Nette have 3.0 version already released for almost all packages

**Comment by vojtamares** [comment]
It has been about year and a half since this issue was opened and no progress in terms of 1.x.y versions was made.

As I came across the documentation of ZeroVer (https://0ver.org/), I suggest we stay with it. And I wish to resolve this issue since it has been open for a long time now.

**Comment by mabar** [comment]
It's a long term issue, no need to solve it immediately.

Using 0.x versions is semver compatible versioning, it has nothing to do with zerover.

**Comment by vojtamares** [comment]
Indeed, I semver is fine with it, on the other hand there was a discussion about it and still some people from time to time come up with a question when we will release a stable version of something.  At least we should make a statement about versioning on our website. So we have a place to redirect people to. 

And not to keep such information for ourselves. Yes, there is this GitHub issue, but honestly, how many people know about it? 

Yes, the web is getting bigger and bigger, but I would say that this kind of information should be written somewhere. And there can be a link to this issue.

**Comment by f3l1x** [comment]
> Side notes... I like ZeroVer ;-)

**Comment by f3l1x** [comment]
At this time we are just fine with ZeroVer.
