### ISSUE TITLE
RFC: phpstan

### ISSUE THREAD

**Issue by f3l1x** [contributte/contributte#41]
This roadmap RFC aims to phpstan standardization.

------

1. Default version of phpstan.

- phpstan/phpstan: ^1.0

2. Default set of phpstan extensions.

-  phpstan/phpstan
-  phpstan/phpstan-deprecation-rules
-  phpstan/phpstan-nette
-  phpstan/phpstan-strict-rules

3. No `phpstan/extension-installer`, load it manually in `phpstan.neon`.

```neon
includes:
	- vendor/phpstan/acme/acme.neon
```

**Comment by petrparolek** [comment]
It should be `phpstan/phpstan: ^1.0`

**Comment by f3l1x** [comment]
Solved.
