### ISSUE TITLE
Contributte Working Group (CWG): community challenge (vol1) 

### ISSUE THREAD

**Issue by f3l1x** [contributte/contributte#45]
**Libraries**

- https://github.com/contributte/nextras-orm-events
- https://github.com/contributte/latte-parsedown-extra
- https://github.com/contributte/database
- https://github.com/contributte/czech-post
- https://github.com/contributte/comgate

**Tasks**

- support PHP 8
- upgrade ninjify/qa: ^0.12
- travis -> github actions
- upgrade phpstan/phpstan v0.12
- remove phpstan/extension-installer
- phpunit ->  nette/tester
- new readme
- update Makefile
- update gitattributes
- update gitignore

**What / How**

Take a look at other contributte library, for example [contributte/oauth2-client](https://github.com/contributte/oauth2-client) and copy-paste / synchronize these files.

**Comment by f3l1x** [comment]
cc @radimvaculik

**Comment by radimvaculik** [comment]
FYI Library https://github.com/contributte/nextras-orm-events done. Working on https://github.com/contributte/czech-post 👌

**Comment by f3l1x** [comment]
Challenge complete!

Heroes: @radimvaculik 

Extra thank you.

![](https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif)
