### ISSUE TITLE
Contributte Working Group (CWG): community challenge (vol2)

### ISSUE THREAD

**Issue by f3l1x** [contributte/contributte#47]
## Goals

- standardise readmes
- travis -> github actions

### Standardise readmes

Steps:

- fork repository
- update README according to https://github.com/contributte/bare
- create PR

Repositories:

- [x] https://github.com/contributte/anabelle
- [x] https://github.com/contributte/api-docu
- [x] https://github.com/contributte/api-router
- [x] https://github.com/contributte/database
- [x] https://github.com/contributte/elasticsearch
- [x] https://github.com/contributte/gopay
- [x] https://github.com/contributte/gopay-inline
- [x] https://github.com/contributte/gosms
- [x] https://github.com/contributte/jsonrpc
- [x] https://github.com/contributte/live-form-validation
- [x] https://github.com/contributte/logging
- [x] https://github.com/contributte/menu-control
- [x] https://github.com/contributte/mobilni-platby
- [x] https://github.com/contributte/nextras-orm-generator
- [x] https://github.com/contributte/psr11-container-interface
- [x] https://github.com/contributte/rabbitmq
- [x] https://github.com/contributte/replacus
- [x] https://github.com/contributte/social
- [x] https://github.com/contributte/thepay
- [x] https://github.com/contributte/thepay-api
- [x] https://github.com/contributte/webpack
- [x] https://github.com/contributte/wordcha

###  Travis -> Github Actions

- [x] [contributte/gopay](https://github.com/contributte/gopay)
- [x] [contributte/gopay-api](https://github.com/contributte/gopay-api)
- [x] [contributte/live-form-validation](https://github.com/contributte/live-form-validation)
- [x] [contributte/forms-wizard](https://github.com/contributte/forms-wizard)
- [x] [contributte/gopay-simple](https://github.com/contributte/gopay-simple)
- [x] [contributte/api-router](https://github.com/contributte/api-router)
- [x] [contributte/commits-site](https://github.com/contributte/commits-site)
- [x] [contributte/jsonrpc](https://github.com/contributte/jsonrpc)
- [x] [contributte/replacus](https://github.com/contributte/replacus)
- [x] [contributte/code-checker](https://github.com/contributte/code-checker)
- [x] [contributte/doctrine-gedmo](https://github.com/contributte/doctrine-gedmo)

**Comment by petrparolek** [comment]
WIP

**Comment by radimvaculik** [comment]
@petrparolek all of them?

**Comment by petrparolek** [comment]
I will make https://github.com/contributte/replacus
https://github.com/contributte/social
https://github.com/contributte/thepay
https://github.com/contributte/thepay-api
https://github.com/contributte/webpack

**Comment by petrparolek** [comment]
I will prepare

https://github.com/contributte/live-form-validation
https://github.com/contributte/logging
https://github.com/contributte/menu-control
https://github.com/contributte/mobilni-platby
https://github.com/contributte/nextras-orm-generator
https://github.com/contributte/psr11-container-interface
https://github.com/contributte/rabbitmq

**Comment by petrparolek** [comment]
@radimvaculik  any progress?

**Comment by petrparolek** [comment]
OK, I will make all of them

**Comment by tomashaubert** [comment]
Hello to everybody. I am added first PR for CWG. [contributte/replacus](https://github.com/contributte/replacus) has in composer only latte dependency. In [contributte/bare](https://github.com/contributte/bare) is column for Nette version. How to write this version if there is no direct dependency on nette/nette or nette/aplication?

Thanks

**Comment by f3l1x** [comment]
Just rename it to Latte. :-)

**Comment by petrparolek** [comment]
I think, it is ready to close this issue @f3l1x

**Comment by f3l1x** [comment]
It's ready to close it. Thank you.
