### ISSUE TITLE
RFC: integrate Apitte into contributte

### ISSUE THREAD

**Issue by f3l1x** [contributte/contributte#50]
This issue is about integration of Apitte (https://github.com/apitte) into the Contributte (https://github.com/contributte).

-----

### How

**Phase 1**

- Move all apitte/* repositories into contributte organization
    - apitte/core => contributte/apitte-core 
    - apitte/debug => contributte/apitte-debug 
    - apitte/openapi => contributte/apitte-openapi 
    - apitte/negotiation => contributte/apitte-negotiation 
    - apitte/middlewares => contributte/apitte-middlewares 
    - apitte/presenter => contributte/apitte-presenter 
    - apitte/events => contributte/apitte-events 
    - apitte/console => contributte/apitte-console 
    - apitte/fullstack => contributte/apitte-fullstack 

**Phase 2**

- Rename contributte/apitte-core to contributte/apitte
    - There is too much stars, issues and history and it make sense to keep it
- Introduce new repository contributte/apitte-core  
- Push contributte/apitte with full history into contributte/apitte-core
- Update packagist URLs to contributte/apitte and contributte/apitte-core
   -  We don't want to break current apps / composers

**Phase 3**

- Merge all contributte/apitte-* into contributte/apitte
    - apitte/core + apitte/debug + apitte/openapi + apitte/negotiation + apitte/middlewares + apitte/presenter + apitte/events + apitte/console   
    - Each repo means 1 commit 
- Deprecate all apitte/* packages on Github
- Abandone all apitte/* packages  on Packagist

**Phase 4**
- Profit

### Motivation

- Focus on one strong brand **contributte**.
- Make development more easier and smooth.
- Prepare for new features.

**Comment by paveljanda** [comment]
I would leave Apitte in separate repository. Just because it is so many repositories already. For example - when there is some serious (:D) development in datarid that contains more and more repositories (more standalone JS implementations, more types of component etc), I would put i into separate namespace/organisation. It could be a mess after a while.

**Comment by paveljanda** [comment]
As discussed in internal channels -> sounds OK to me if all packages will be merged into one. 👍

**Comment by f3l1x** [comment]
Solved.
