### ISSUE TITLE
RFC: integrate Nettrine into contributte

### ISSUE THREAD

**Issue by f3l1x** [contributte/contributte#51]
This issue is about integration of Nettrine (https://github.com/nettrine) into the Contributte (https://github.com/contributte).

-----

### How

**Phase 1**

- Move all nettrine/* repositories into contributte organization
    - nettrine/dbal => contributte/doctrine-dbal 
    - nettrine/orm => contributte/doctrine-orm 
    - nettrine/migrations => contributte/doctrine-migrations 
    - nettrine/fixtures => contributte/doctrine-fixtures 
    - nettrine/cache => contributte/doctrine-cache 
    - nettrine/annotations => contributte/doctrine-annotations 
    - nettrine/odm => contributte/doctrine-odm 
    - nettrine/mongodb => contributte/doctrine-mongodb 
    - nettrine/extensions-atlantic18 => contributte/doctrine-extensions-atlantic18 
    - nettrine/extensions-beberlei => contributte/doctrine-extensions-beberlei 
    - nettrine/extensions-knplabs => contributte/doctrine-extensions-knplabs 
    - nettrine/extensions-oroinc => contributte/doctrine-extensions-oroinc 

**Phase 2**

- Release latest versions for all packages

**Phase 3**

- Rename namespace Nettrine\{PKG}\* to Contributte\Doctrine\{PKG}*

**Phase 4**

- Rename composer package name to match repository name
    - nettrine/dbal => contributte/doctrine-dbal 
    - nettrine/orm => contributte/doctrine-orm 
    - nettrine/migrations => contributte/doctrine-migrations 
    - nettrine/fixtures => contributte/doctrine-fixtures 
    - nettrine/cache => contributte/doctrine-cache 
    - nettrine/annotations => contributte/doctrine-annotations 
    - nettrine/odm => contributte/doctrine-odm 
    - nettrine/mongodb => contributte/doctrine-mongodb 
    - nettrine/extensions-atlantic18 => contributte/doctrine-extensions-atlantic18 
    - nettrine/extensions-beberlei => contributte/doctrine-extensions-beberlei 
    - nettrine/extensions-knplabs => contributte/doctrine-extensions-knplabs 
    - nettrine/extensions-oroinc => contributte/doctrine-extensions-oroinc 

**Phase 5**

- Profit

### Motivation

- Focus on one strong brand **contributte**.
- Don’t force people to watch more organizations. 
- Name packages more predictable for people (e.q. contributte/doctrine-orm).

**Comment by f3l1x** [comment]
My question is. Should we rename composer name (for example nettrine/dbal => contributte/doctrine-dbal) or should be keep original (for example nettrine/dbal)?

- Rename 🚀 
- Keep 😕

**Comment by petrparolek** [comment]
why?

**Comment by f3l1x** [comment]
It's in the first post under `Motivation`.

**Comment by paveljanda** [comment]
I have the same opinion as in #50. Putting 20 repositories with almost same name into Contributte does not make any sense to me. When it is a monorepo, OK. But in this case, it should be a standalone organisation. Do not forget to make thing readable. :) Newcomers dont tend to list over all 20 pages of OSS organisation repositories..

**Comment by paveljanda** [comment]
As discussed in internal channels -> sounds OK to me if want to prefer support from companies. If we want to prefer newbies, maybe letting nettrine package sit in separate org would bring more GitHub stars. :D But it looks like companies will won 👍

**Comment by f3l1x** [comment]
Work is done. 

----

Composer packages stay with nettrine/* for now.
Namespaces stay with Nettrine/* for now.
