### ISSUE TITLE
New Truster: MALL.CZ

### ISSUE THREAD

**Issue by danielrataj** [contributte/contributte#52]
# New Truster

- Name: MALL.CZ
- URL: https://www.mall.cz/
- Image: ![mall-it-logo](https://user-images.githubusercontent.com/13363668/116869782-a524b580-ac11-11eb-8734-92843f8509eb.jpg)

We use Contributte packages and Nette itself as a core for all MALL e-shops across countries and microservices related to products.

**Comment by f3l1x** [comment]
❤️ 
![image](https://user-images.githubusercontent.com/538058/117133805-0335d200-ada5-11eb-9678-753ed25d77af.png)
