### ISSUE TITLE
MI:SU Design s.r.o.

### ISSUE THREAD

**Issue by ferencik-f** [contributte/contributte#55]
# New Truster

- Name: MI:SU Design s.r.o.
- URL: https://www.misudesign.sk
- Image: https://i.ibb.co/sHjNKGW/misu-logo-512x512-02.png

**Comment by f3l1x** [comment]
![image](https://user-images.githubusercontent.com/538058/145104461-081501a0-5b5d-430c-bfad-7d0ae4ddc10e.png)

Thank you :-)
